Repository Enthusiastic-Developer/Hypercare, pull requests merged in 2024-01, with the labels that each got.

#21 Added the Delete API for CareOpsController
  BackEnd/CareOpsManager/CareOpsManagerAPI/Controllers/CareOpsController.cs
  BackEnd/CareOpsManager/CareOpsManagerInterfaces/ICareOpsManagerService.cs
  BackEnd/CareOpsManager/CareOpsManagerService.NunitTest/CareOpsControllerTest.cs
  BackEnd/CareOpsManager/CareOpsManagerService.NunitTest/CareOpsManagerClient.cs
  BackEnd/CareOpsManager/CareOpsManagerService/BLL/CareOps.cs
  BackEnd/CareOpsManager/CareOpsManagerService/BusinessObjects/CareOps.cs
  BackEnd/CareOpsManager/CareOpsManagerService/DAL/CareOps.cs
  CommonLibraries/CareOpsManagerService.dll
  Misc/SQLScripts/DDL/Stored Procedures/DeleteAndArchiveHyperCareSchedulerSPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/DeleteAndArchiveHyperCareTaskMasterSPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/DeleteAndArchiveHypercareResponsibleTeamSPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/DeleteAndArchiveHypercareTaskSchedulerMapSPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/InsertHypercareResponsibleTeamSPDDL.sql
  Misc/SQLScripts/DDL/Tables/HyperCareScheduler_HistoryDDL.sql
  Misc/SQLScripts/DDL/Tables/HyperCareTaskMaster_HistoryDDL.sql
  Misc/SQLScripts/DDL/Tables/HypercareResponsibleTeam_HistoryDDL.sql
  Misc/SQLScripts/DDL/Tables/HypercareTaskSchedulerMap_HistoryDDL.sql
Labels: enhancement

#24 Added the Delete API for CronCraftController
  BackEnd/CronCraft/CronCraftAPI/Controllers/CronCraftController.cs
  BackEnd/CronCraft/CronCraftInterfaces/ICronCraftService.cs
  BackEnd/CronCraft/CronCraftService.NunitTest/CronCraftClient.cs
  BackEnd/CronCraft/CronCraftService.NunitTest/CronCraftControllerTest.cs
  BackEnd/CronCraft/CronCraftService/BLL/CronCraft.cs
  BackEnd/CronCraft/CronCraftService/BusinessObjects/CronCraft.cs
  BackEnd/CronCraft/CronCraftService/DAL/CronCraft.cs
  CommonLibraries/CronCraftService.dll
Labels: Development

#25 Added the Delete API for MappingController
  BackEnd/MappingEngine/MappingEngineAPI/Controllers/MappingController.cs
  BackEnd/MappingEngine/MappingEngineInterfaces/IMappingEngineService.cs
  BackEnd/MappingEngine/MappingEngineService.NunitTest/MappingControllerTest.cs
  BackEnd/MappingEngine/MappingEngineService.NunitTest/MappingEngineClient.cs
  BackEnd/MappingEngine/MappingEngineService/BLL/MappingEngine.cs
  BackEnd/MappingEngine/MappingEngineService/BusinessObjects/MappingEngine.cs
  BackEnd/MappingEngine/MappingEngineService/DAL/MappingEngine.cs
  CommonLibraries/MappingEngineService.dll
Labels: Development

#26 Added the Delete API for TeamController
  BackEnd/TeamProfiles/TeamProfilesAPI/Controllers/TeamController.cs
  BackEnd/TeamProfiles/TeamProfilesInterfaces/ITeamProfileService.cs
  BackEnd/TeamProfiles/TeamProfilesService.NunitTest/TeamControllerTest.cs
  BackEnd/TeamProfiles/TeamProfilesService.NunitTest/TeamProfileClient.cs
  BackEnd/TeamProfiles/TeamProfilesService/BLL/TeamProfile.cs
  BackEnd/TeamProfiles/TeamProfilesService/BusinessObjects/TeamProfile.cs
  BackEnd/TeamProfiles/TeamProfilesService/DAL/TeamProfile.cs
  CommonLibraries/TeamProfilesService.dll
Labels: Development

#31 All the API's are developed and tested
  BackEnd/History/HistoryAPI/Controllers/HistoryController.cs
  BackEnd/History/HistoryAPI/HistoryAPI.csproj
  BackEnd/History/HistoryInterfaces/HistoryInterfaces.csproj
  BackEnd/History/HistoryInterfaces/IHistoryService.cs
  BackEnd/History/HistoryService.NunitTest/HistoryClient.cs
  BackEnd/History/HistoryService.NunitTest/HistoryControllerTest.cs
  BackEnd/History/HistoryService.NunitTest/HistoryService.NunitTest.csproj
  BackEnd/History/HistoryService.NunitTest/Usings.cs
  BackEnd/History/HistoryService/BLL/History.cs
  BackEnd/History/HistoryService/BusinessObjects/History.cs
  BackEnd/History/HistoryService/DAL/History.cs
  BackEnd/History/HistoryService/HistoryService.csproj
  CommonLibraries/CareOpsManagerService.dll
  CommonLibraries/CronCraftService.dll
  CommonLibraries/DashboardService.dll
  CommonLibraries/HistoryService.dll
  CommonLibraries/MappingEngineService.dll
  CommonLibraries/ModelService.dll
  CommonLibraries/TeamProfilesService.dll
  HypercareCore/ModelService/Common/Pagination.cs
  Misc/SQLScripts/DDL/Stored Procedures/GetHyperCareTrackerDataByDateRangeSPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/GetHyperCareTrackerDataBySchIdSPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/GetHyperCareTrackerDataByTaskIdSPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/GetHyperCareTrackerDataSPDDL.sql
Labels: Development

#35 All the API's are developed and tested
  BackEnd/Dashboard/DashboardAPI/Controllers/DashboardController.cs
  BackEnd/Dashboard/DashboardAPI/DashboardAPI.csproj
  BackEnd/Dashboard/DashboardInterfaces/DashboardInterfaces.csproj
  BackEnd/Dashboard/DashboardInterfaces/IDashboardService.cs
  BackEnd/Dashboard/DashboardService.NunitTest/DashboardClient.cs
  BackEnd/Dashboard/DashboardService.NunitTest/DashboardControllerTest.cs
  BackEnd/Dashboard/DashboardService.NunitTest/DashboardService.NunitTest.csproj
  BackEnd/Dashboard/DashboardService.NunitTest/Usings.cs
  BackEnd/Dashboard/DashboardService/BLL/Dashboard.cs
  BackEnd/Dashboard/DashboardService/BusinessObjects/Dashboard.cs
  BackEnd/Dashboard/DashboardService/DAL/Dashboard.cs
  BackEnd/Dashboard/DashboardService/DashboardService.csproj
  CommonLibraries/CareOpsManagerService.dll
  CommonLibraries/ConfigurationService.dll
  CommonLibraries/CronCraftService.dll
  CommonLibraries/DashboardService.dll
  CommonLibraries/HistoryService.dll
  CommonLibraries/MappingEngineService.dll
  CommonLibraries/ModelService.dll
  CommonLibraries/TeamProfilesService.dll
  HypercareCore/ConfigurationService/ConfigSettings.cs
  HypercareCore/ConfigurationService/ConnectionManager.cs
  HypercareCore/ModelService/Dashboard/DailyCount.cs
  HypercareCore/ModelService/Dashboard/IssueMetrics.cs
  HypercareCore/ModelService/Dashboard/ModuleStatistics.cs
  Misc/Diagrams/Pages-Needed.drawio
  Misc/SQLScripts/DDL/Stored Procedures/GetHyperCareIssueStatisticsForDaySPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/GetHyperCareIssueStatisticsForDaysSPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/GetHyperCareModuleStatisticsForDaySPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/GetHyperCareModuleStatisticsForDaysSPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/GetHyperCareOperationsCountForDaySPDDL.sql
  Misc/SQLScripts/DDL/Stored Procedures/GetHyperCareOperationsCountForDaysSPDDL.sql
Labels: Development

#38 #36 Ugraded vulnerable packages and other updatable packages and all…
  BackEnd/CareOpsManager/CareOpsManagerAPI/CareOpsManagerAPI.csproj
  BackEnd/CareOpsManager/CareOpsManagerService.NunitTest/CareOpsManagerService.NunitTest.csproj
  BackEnd/CronCraft/CronCraftAPI/CronCraftAPI.csproj
  BackEnd/CronCraft/CronCraftService.NunitTest/CronCraftService.NunitTest.csproj
  BackEnd/Dashboard/DashboardAPI/DashboardAPI.csproj
  BackEnd/Dashboard/DashboardService.NunitTest/DashboardService.NunitTest.csproj
  BackEnd/History/HistoryAPI/HistoryAPI.csproj
  BackEnd/History/HistoryService.NunitTest/HistoryService.NunitTest.csproj
  BackEnd/MappingEngine/MappingEngineAPI/MappingEngineAPI.csproj
  BackEnd/MappingEngine/MappingEngineService.NunitTest/MappingEngineService.NunitTest.csproj
  BackEnd/TeamProfiles/TeamProfilesAPI/TeamProfilesAPI.csproj
  BackEnd/TeamProfiles/TeamProfilesService.NunitTest/TeamProfilesService.NunitTest.csproj
  CommonLibraries/CareOpsManagerService.dll
  CommonLibraries/CommonService.dll
  CommonLibraries/ConfigurationService.dll
  CommonLibraries/CronCraftService.dll
  CommonLibraries/DashboardService.dll
  CommonLibraries/HistoryService.dll
  CommonLibraries/LoggingService.dll
  CommonLibraries/MappingEngineService.dll
  CommonLibraries/ModelService.dll
  CommonLibraries/TeamProfilesService.dll
  HypercareCore/ConfigurationService/ConfigurationService.csproj
  HypercareCore/LoggingService/LoggingService.csproj
  ServiceJobs/DataArchival/DataArchival/DataArchival.csproj
Labels: dependencies
